# This is a basic workflow to help you get started with Actions



name: Readme Update

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # schedule:
  #   # - cron: "0 0 12 ? * WED *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser
      - name: Update README
        run: |
          python read_rss.py

      - name: Commit README
        run: |
          git add .
          git config --local user.email "@gmail.com"
          git config --local user.name "svng-zu"
          git commit -m "Update README.md"
          git push origin +master
